services:
  web:
    image: avogadrod/flask-app:latest
    build: .
    expose:
      - "5000"
    deploy:
      replicas: 3
    environment:
      - CONTAINER_ID=something
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web